repos:
  - repo: https://github.com/Lucas-C/pre-commit-hooks
    rev: v1.5.5
    hooks:
      - id: forbid-crlf
      - id: remove-crlf
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v6.0.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-merge-conflict
      - id: check-toml
      - id: check-yaml
        exclude: helm/
        args: [ --unsafe ]
  - repo: https://github.com/charliermarsh/ruff-pre-commit
    rev: "v0.12.9"
    hooks:
      - id: ruff
        args: [--fix, --exit-non-zero-on-fix]
      - id: ruff-format
  - repo: https://github.com/MarcoGorelli/cython-lint
    rev: v0.16.7
    hooks:
    -   id: cython-lint
    -   id: double-quote-cython-strings
